name: github-CI

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        python-version: [3.6, 3.7, 3.8]
    name: Python ${{ matrix.python-version }} example
    
    steps:
    - uses: actions/checkout@v2
    - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
    - name: setup-conda
      uses: s-weigand/setup-conda@v1.0.2
      with:
          update-conda: true
          python-version: ${{ matrix.python-version }}
          conda-channels: anaconda, conda-forge
    - run: conda --version
    - run: which python
    - run: |
        conda config --add channels conda-forge
        conda config --set always_yes yes
        conda install -n root conda-build numpy
        conda build ./conf/conda
